runtime: go
api_version: go1

handlers:

# If the path is empty, show static index.html file
- url: /
  static_files: dist/index.html
  upload: dist/index.html

# Otherwise, find file in static directory
- url: /
  static_dir: dist

# [END static_handlers]  
- url: /.*
  script: _go_app

skip_files:
- ^(.*/)?node_modules
